name: CI BASIC
on:
  push: branches:[main]
  pull_request: branches:[main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Current Directory
        run: pwd
      - name: List files
        run: ls -la
      - name: Node version
        run: node -v
      - name: Npm version
        run: npm -v
